### PR TITLE
Update and rename MainActivity.java to LoginActivity.java

### PR DESCRIPTION
**Pull request by jwu-labs**
Hi Phyllis, could you see if this runs on your program?

### CODE REVIEW

**Comment by phyllisfeng** [comment]
Hi Joyce,
I will try to look at this tonight.
cheersPhyllisDate: Wed, 22 Apr 2015 23:18:09 -0700

**Comment by phyllisfeng** [comment]
Hi Joyce,
im getting problems on files I haven't had problem before :(  userlogin and create account etc used to be working fine but now having "rendering problem" ...don't know why.
how's at your end?phyllisDate: Wed, 22 Apr 2015 23:18:09 -0700

**Comment by jwu-labs** [comment]
Hi Phyllis,

Sorry, I think I accidentally muted the onCreateOptionsMenu and
onOptionsItemSelected
methods at the bottom of LoginActivity.java. Could you delete the /\* and */
to make it active again?

I am thinking about taking the LoginActivity page and separate it to two
pages: one for sign in to existing account and one for sign up for a new
account.

Also, similar to the example, we can have a page with choices to create new
game, join existing game, or view my game

As for the user creation of the game, I'm thinking if we can do two pages
for it as well.
The first page will contain the following fields:
1. ask for name of the new game
2. ask for game start time
3. ask for game end time
4. ask for number of items to find

The second page will ask user's input for the items to find, and the number
of fields will depends on #4 in first page.

Do you think this is do-able?

Thanks,
-Joyce

**Comment by phyllisfeng** [comment]
Joyce, no problem!
Ive created parse tables , let me know if okay before we submit

I agree to break down pages for users, pls see my draft of UI.

Sent from Samsung tabletfoxy9145 notifications@github.com wrote:Hi Phyllis,

Sorry, I think I accidentally muted the onCreateOptionsMenu and
onOptionsItemSelected
methods at the bottom of LoginActivity.java. Could you delete the /\* and */
to make it active again?

I am thinking about taking the LoginActivity page and separate it to two
pages: one for sign in to existing account and one for sign up for a new
account.

Also, similar to the example, we can have a page with choices to create new
game, join existing game, or view my game

As for the user creation of the game, I'm thinking if we can do two pages
for it as well.
The first page will contain the following fields:
1. ask for name of the new game
2. ask for game start time
3. ask for game end time
4. ask for number of items to find

The second page will ask user's input for the items to find, and the number
of fields will depends on #4 in first page.

Do you think this is do-able?

Thanks,
-Joyce

**Comment by jwu-labs** [comment]
Hi Phyllis,

Where can I see the parse table and your draft UI?

Regards,
-Joyce

**Pull request closed without merging**
